# Wrangler configuration for Cloudflare Pages
name = "flux-image-generator"
compatibility_date = "2024-01-01"

# This is a static site - no build process needed
# Files are deployed directly from the repository root