# Wrangler configuration for Cloudflare Pages
name = "freeai-app-2024"
compatibility_date = "2024-12-15"

# Pages configuration
pages_build_output_dir = "."

# Custom domain configuration
[[pages.custom_domains]]
domain = "freegen.r0b.cc"