name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PROJECT_NAME: freeai-app-2024

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (for any future build steps)
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Validate HTML files
        run: |
          echo "Validating HTML structure..."
          # Simple validation to ensure files exist and are not empty
          if [ ! -f "index.html" ]; then
            echo "Error: index.html not found"
            exit 1
          fi
          if [ ! -s "index.html" ]; then
            echo "Error: index.html is empty"
            exit 1
          fi
          echo "HTML validation passed"

      - name: Create Cloudflare Pages Project (if needed)
        uses: cloudflare/wrangler-action@v3
        continue-on-error: true
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages project create ${{ env.PROJECT_NAME }} --production-branch main

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy . --project-name=${{ env.PROJECT_NAME }} --commit-dirty=true

      - name: Add deployment summary
        run: |
          echo "## 🚀 Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Project**: ${{ env.PROJECT_NAME }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ✅ Deployed successfully" >> $GITHUB_STEP_SUMMARY
          echo "- **Custom Domain**: https://freegen.r0b.cc" >> $GITHUB_STEP_SUMMARY
          echo "- **Pages URL**: https://${{ env.PROJECT_NAME }}.pages.dev" >> $GITHUB_STEP_SUMMARY